services:
  rdn_connector:
    build:
      context: .
      dockerfile: connectors/rdn/Dockerfile
    working_dir: /app/connectors/rdn
    volumes:
      - .:/app
      - rdn_bundle:/home/app/bundle
    env_file:
      - .env
    stdin_open: true
    tty: true


  ofac_loan_export:
    build:
      context: .
      dockerfile: connectors/ofac_loan_export/Dockerfile
    working_dir: /app/connectors/ofac_loan_export
    volumes:
      - .:/app
      - ./lib:/app/lib
    env_file:
      - .env
    stdin_open: true
    tty: true

# New solution
# other_solution:
#   build: .
#   working_dir: /app/solutions/other_solution
#   volumes:
#     - .:/app
#   stdin_open: true
#   tty: true

volumes:
  rdn_bundle:
